# Generated by Django 3.1.2 on 2021-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnowLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=7)),
                ('name', models.CharField(max_length=255)),
                ('snow_now', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
